/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo_JNIDemoJava */

#ifndef _Included_jnidemo_JNIDemoJava
#define _Included_jnidemo_JNIDemoJava
#ifdef __cplusplus
extern "C" {
#endif
#undef jnidemo_JNIDemoJava_REPETITIONS
#define jnidemo_JNIDemoJava_REPETITIONS 100000000L
/*
 * Class:     jnidemo_JNIDemoJava
 * Method:    nativeCrash
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnidemo_JNIDemoJava_nativeCrash
  (JNIEnv *, jobject);

/*
 * Class:     jnidemo_JNIDemoJava
 * Method:    nativePrint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnidemo_JNIDemoJava_nativePrint
  (JNIEnv *, jobject);

/*
 * Class:     jnidemo_JNIDemoJava
 * Method:    nativeSleep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jnidemo_JNIDemoJava_nativeSleep
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnidemo_JNIDemoJava
 * Method:    nativeAllocate
 * Signature: (I)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_jnidemo_JNIDemoJava_nativeAllocate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
